### ISSUE TITLE
NullPointerExceptions during websocket use

### ISSUE THREAD

**Issue by deruelle** [Mobicents/jain-sip#2]
We've noticed occasional NullPointerExceptions such as:

java.lang.NullPointerException: null 
at gov.nist.javax.sip.stack.NioWebSocketMessageChannel.processMessage(NioWebSocketMessageChannel.java:280) ~[jain-sip-ri-1.2.1-SNAPSHOT.jar:1.2.1-SNAPSHOT] 
at gov.nist.javax.sip.parser.NioPipelineParser$Dispatch.run(NioPipelineParser.java:175) ~[jain-sip-ri-1.2.1-SNAPSHOT.jar:1.2.1-SNAPSHOT] 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_55] 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_55] 
at java.lang.Thread.run(Thread.java:745) [na:1.7.0_55]

The exception being caused by calling NioWebsocketMessageChannel.processMessage(null).  StringMsgParser.parseSIPMessage() returns null in some cases for the non NIO case instead of throwing a ParseException so the null case needs to be handled in the NIO case as well.

Turning up the debugging the unparsed message seems to be the same every time and prints as follows: 
""" 
2015-07-15 15:24:16,136 DEBUG [SIP-TCP-Core-PipelineThreadpool-4] gov.nist.javax.sip.parser.NioPipelineParser - 
Unparsed message before parser is: 
gov.nist.javax.sip.parser.NioPipelineParser$UnparsedMessage@78e461bf 
^C�

""" 
some quick xxd output: 
0529830: 7365 722e 4e69 6f50 6970 656c 696e 6550 ser.NioPipelineP 
0529840: 6172 7365 7224 556e 7061 7273 6564 4d65 arser$UnparsedMe 
0529850: 7373 6167 6540 3738 6534 3631 6266 0a03 ssage@78e461bf.. 
0529860: efbf bd0d 0a0d 0a0a 3230 3135 2d30 372d ........2015-07-

so I think the actual message is: 03ef bfbd 0d0a 0d0a (since UnparsedMessage adds a newline in its toString). I have no idea what 03ef bfbd is supposed to be, maybe something websocket-related.

**Comment by deruelle** [comment]
https://telestax.atlassian.net/browse/JSIP-28
