### ISSUE TITLE
SDP parsing problem on Chrome 46

### ISSUE THREAD

**Issue by hrosa** [Mobicents/jain-sip#6]
WebRTC calls are broken on Mobicents RestComm 7.3.x when using Chrome 46.

The current version of Chrome uses a new RTP profile, UDP/TLS/RTP/SAVPF, which [jain-sip cannot parse] (https://gist.github.com/hrosa/52f70dbc33718d66515c).

The entire SDP offer generated by Chrome can be found [here] (https://gist.github.com/hrosa/42cf0547e839dd643127)

**Comment by gvagenas** [comment]
Restcomm exception:
```
05:23:44,061 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572) java.text.ParseException: m=audio 58335 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
05:23:44,061 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at gov.nist.javax.sdp.parser.MediaFieldParser.mediaField(MediaFieldParser.java:123)
05:23:44,061 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at gov.nist.javax.sdp.parser.MediaFieldParser.parse(MediaFieldParser.java:130)
05:23:44,061 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at gov.nist.javax.sdp.parser.SDPAnnounceParser.parse(SDPAnnounceParser.java:109)
05:23:44,062 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at javax.sdp.SdpFactory.createSessionDescription(SdpFactory.java:131)
05:23:44,062 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at org.mobicents.servlet.restcomm.telephony.Call.patch(Call.java:852)
05:23:44,062 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at org.mobicents.servlet.restcomm.telephony.Call.access$2500(Call.java:119)
05:23:44,062 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at org.mobicents.servlet.restcomm.telephony.Call$OpeningRemoteConnection.execute(Call.java:1123)
05:23:44,062 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at org.mobicents.servlet.restcomm.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:83)
05:23:44,063 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at org.mobicents.servlet.restcomm.telephony.Call.onReceive(Call.java:599)
05:23:44,063 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159)
05:23:44,063 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425)
05:23:44,063 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at akka.actor.ActorCell.invoke(ActorCell.scala:386)
05:23:44,064 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230)
05:23:44,064 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at akka.dispatch.Mailbox.run(Mailbox.scala:212)
05:23:44,064 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506)
05:23:44,064 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262)
05:23:44,064 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
05:23:44,065 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
05:23:44,065 ERROR [stderr] (RestComm-akka.actor.default-dispatcher-18572)       at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
```

**Comment by hrosa** [comment]
Updating to latest version of jain-sip (1.2.245) dependency solved the issue for me.

**Comment by gvagenas** [comment]
Thanks for reporting that @hrosa , I will update the jain-sip library

**Comment by gvagenas** [comment]
Nothing to do here.
Restcomm issue https://github.com/Mobicents/RestComm/issues/542
